[package]
name = "angles"
version = "0.1.0"
authors = ["Jordan Bray <jordan@northwoodmachine.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.20.0" }
num = "0.2.1"
num-traits = "0.2.1"
num-integer = "0.1.42"
quickcheck = "0.9.1"
quickcheck_macros = "0.9.1"
